name: CI - Custom Manual Builder (Win7)

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: |
          Target Commit SHA, Tag, or Branch to build (Leave blank for latest, see Notes bellow). Selected commit must have this workflow otherwise the latest commit will be built instead of the one you put here:
        required: false
        default: ''

      toolchain:
        description: 'Select the toolchain to build with:'
        required: true
        type: choice
        default: 'msvc'
        options:
          - 'msvc'
          - 'llvm_msvc'
          - 'llvm_mingw'
          - 'mingw'
      platform:
        description: 'Select Target Architecture / Instruction Set:'
        required: true
        type: choice
        default: 'x64'
        options:
          - 'Win32'
          - 'x64'
          - 'ARM64'
          - 'AVX2'
          - 'AVX512'
      msvc_version:
        description: 'If using MSVC, select Visual Studio version (ignored for MinGW):'
        required: true
        type: choice
        default: '2022'
        options:
          - '2022'
          - '2026'
      mingw_arch:
        description: 'If using Standard MinGW, select CRT runtime (ignored for MSVC):'
        required: true
        type: choice
        default: 'x86_64'
        options:
          - 'x86_64'
          - 'ucrt'
          - 'i686'
      mingw_compiler:
        description: 'If using Standard MinGW, select Compiler (ignored for MSVC):'
        required: true
        type: choice
        default: 'GCC'
        options:
          - 'GCC'
          - 'Clang'

      Note1:
        description: |
          - Note1: The GitHub Actions summary page has a visual limitation: the header banner, run title, and commit badge always display the latest commit of the triggering branch, regardless of what happens inside the runner. Even if actions/checkout successfully pulls down your specific commit SHA and switches your codebase back in time, the top of the GitHub UI will still show the latest commit hash. 
          The Fix: To prove exactly what code is being built, I added a quick verification step immediately after the checkout step to log the real HEAD, and the final zip will contain the commit ref too.
        required: false
        default: ''
        
      Note2:
        description: |
          - Note2: When you trigger a workflow manually via workflow_dispatch, GitHub reads the workflow YAML file strictly from the branch selected in the "Use workflow from" dropdown.
          If your new configuration changes (the ones handling the git_ref input) are currently sitting on a feature branch and haven't been merged to main yet, leaving that dropdown on main will cause GitHub to execute the old version of your workflow. The old version has no idea the input box exists, so it completely ignores whatever you typed and builds the latest commit of main.
          The Fix: Ensure the "Use workflow from" dropdown matches the exact branch where your updated workflow file lives.
        required: false
        default: ''
        
        
        
defaults:
  run:
    shell: cmd

jobs:
  # ==========================================
  # 1. MSVC & LLVM-MSVC JOB
  # ==========================================
  msvc_builds:
    if: ${{ github.event.inputs.toolchain == 'msvc' || github.event.inputs.toolchain == 'llvm_msvc' }}
    name: MSVC ${{ github.event.inputs.msvc_version }} (${{ github.event.inputs.platform }})
    runs-on: ${{ github.event.inputs.msvc_version == '2026' && 'windows-2025-vs2026' || 'windows-2022' }}
    steps:
    - name: Checkout Custom Ref
      if: github.event.inputs.git_ref != ''
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.git_ref }}
        fetch-depth: 0

    - name: Checkout Default
      if: github.event.inputs.git_ref == ''
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Actual Commit SHA
      shell: bash
      run: |
        echo "REAL_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

    - name: Update Version Hash
      run: |
        "c:/Program Files/Git/usr/bin/sed" -i "s/^\(.\+\)[0-9a-f]\{8\}\(.\+\)$/\1%REAL_SHA:~0,8%\2/gm" ./src/VersionRev.h ./matepath/src/VersionRev.h

    - name: Run Install LLVM (Only if LLVM-MSVC selected)
      if: ${{ github.event.inputs.toolchain == 'llvm_msvc' }}
      run: |
        CALL "build\install_llvm.bat" latest 1

    - name: Compile MSVC Native
      if: ${{ github.event.inputs.toolchain == 'msvc' }}
      run: |
        CALL "build\VisualStudio\build.bat" Build ${{ github.event.inputs.platform }} Release 1
        CALL "locale\build.bat" Build ${{ github.event.inputs.platform }} Release 1
        CALL "build\make_zip.bat" MSVC ${{ github.event.inputs.platform }} Release Locale 1

    - name: Compile LLVM MSVC Clang
      if: ${{ github.event.inputs.toolchain == 'llvm_msvc' }}
      run: |
        CALL "build\VisualStudio\build.bat" Build ${{ github.event.inputs.platform }} LLVMRelease 1
        CALL "build\make_zip.bat" LLVM ${{ github.event.inputs.platform }} Release 1

    - name: Upload Native MSVC Artifact
      if: ${{ github.event.inputs.toolchain == 'msvc' }}
      uses: actions/upload-artifact@v4
      with:
          name: Notepad4_MSVC${{ github.event.inputs.msvc_version }}_i18n_${{ github.event.inputs.platform }}_${{ env.SHORT_SHA }}
          path: 'build\Notepad4_i18n_${{ github.event.inputs.platform }}_*.zip'

    - name: Upload LLVM MSVC Artifact
      if: ${{ github.event.inputs.toolchain == 'llvm_msvc' }}
      uses: actions/upload-artifact@v4
      with:
          name: Notepad4_Clang_MSVC${{ github.event.inputs.msvc_version }}_en_${{ github.event.inputs.platform }}_${{ env.SHORT_SHA }}
          path: 'build\Notepad4_LLVM_${{ github.event.inputs.platform }}_*.zip'

  # ==========================================
  # 2. LLVM MINGW JOB
  # ==========================================
  llvm_mingw_builds:
    if: ${{ github.event.inputs.toolchain == 'llvm_mingw' }}
    name: LLVM-MinGW (${{ github.event.inputs.platform }})
    runs-on: windows-latest
    steps:
    - name: Checkout Custom Ref
      if: github.event.inputs.git_ref != ''
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.git_ref }}
        fetch-depth: 0

    - name: Checkout Default
      if: github.event.inputs.git_ref == ''
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Actual Commit SHA
      shell: bash
      run: |
        echo "REAL_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

    - name: Update Version Hash
      run: |
        "c:/Program Files/Git/usr/bin/sed" -i "s/^\(.\+\)[0-9a-f]\{8\}\(.\+\)$/\1%REAL_SHA:~0,8%\2/gm" ./src/VersionRev.h ./matepath/src/VersionRev.h

    - name: Install llvm-mingw
      run: |
        CALL "build\install_mingw.bat" llvm

    - name: Clang Release Compilation
      run: |
        CALL "build\mingw\build.bat" llvm ${{ github.event.inputs.platform }}
        CALL "build\make_zip.bat" Clang ${{ github.event.inputs.platform }} Release 1

    - uses: actions/upload-artifact@v4
      with:
          name: Notepad4_llvm_mingw_en_${{ github.event.inputs.platform }}_${{ env.SHORT_SHA }}
          path: 'build\Notepad4_Clang_${{ github.event.inputs.platform }}_*.zip'

  # ==========================================
  # 3. STANDARD MINGW JOB (GCC / CLANG)
  # ==========================================
  mingw_standard_builds:
    if: ${{ github.event.inputs.toolchain == 'mingw' }}
    name: MinGW ${{ github.event.inputs.mingw_arch }} ${{ github.event.inputs.mingw_compiler }} (${{ github.event.inputs.platform }})
    runs-on: windows-latest
    continue-on-error: true
    steps:
    - name: Checkout Custom Ref
      if: github.event.inputs.git_ref != ''
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.git_ref }}
        fetch-depth: 0

    - name: Checkout Default
      if: github.event.inputs.git_ref == ''
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Actual Commit SHA
      shell: bash
      run: |
        echo "REAL_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

    - name: Update Version Hash
      run: |
        "c:/Program Files/Git/usr/bin/sed" -i "s/^\(.\+\)[0-9a-f]\{8\}\(.\+\)$/\1%REAL_SHA:~0,8%\2/gm" ./src/VersionRev.h ./matepath/src/VersionRev.h

    - name: Install Toolchain Environment
      run: |
        CALL "build\install_mingw.bat" ${{ github.event.inputs.mingw_arch }} ${{ github.event.inputs.mingw_compiler }}

    - name: Compile Binary Variant
      run: |
        CALL "build\mingw\build.bat" ${{ github.event.inputs.mingw_arch }} ${{ github.event.inputs.platform }} ${{ github.event.inputs.mingw_compiler }}
        CALL "build\make_zip.bat" ${{ github.event.inputs.mingw_compiler }} ${{ github.event.inputs.platform }} Release 1

    - uses: actions/upload-artifact@v4
      with:
          name: Notepad4_${{ github.event.inputs.mingw_compiler }}${{ github.event.inputs.mingw_compiler == 'Clang' && '_mingw' || '' }}_en_${{ github.event.inputs.platform }}${{ github.event.inputs.mingw_arch == 'ucrt' && '_ucrt' || '' }}_${{ env.SHORT_SHA }}
          path: 'build\Notepad4_${{ github.event.inputs.mingw_compiler }}_${{ github.event.inputs.platform }}_*.zip'